version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=production
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8000
    ports:
      - "3000:80"
    restart: always

